name: Improvement Report
description: Create an improvement report from the application
labels: 
  - improvement
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following sections to help us understand the improvement you are suggesting. If you have any screenshots or additional context, feel free to include them as well.
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A brief title for the bug report
      placeholder: e.g., "App crashes on startup when clicking the login button"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the bug, including steps to reproduce it
      placeholder: e.g., "1. Open the app\n2. Click on the login button\n3. Observe that the app crashes"
    validations:
      required: true
